#ifndef SIGNALRHTTP_GLOBAL_H
#define SIGNALRHTTP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALRHTTP_LIBRARY)
#  define SIGNALRHTTPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALRHTTPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALRHTTP_GLOBAL_H
